### ISSUE TITLE
Firefox not found

### ISSUE THREAD

**Issue by sal123-droid** [mozilla/openwpm-crawler#56]
Hey
I just install the openWPM crawler on my mac following the installation guide mentioned in the readme...
I'm using the docker-compose installation and when I'm trying to run the first crawl I'm getting this error:

> crawler_1     | The above exception was the direct cause of the following exception:
crawler_1     | 
crawler_1     | Traceback (most recent call last):
crawler_1     |   File "/opt/OpenWPM/crawler.py", line 109, in <module>
crawler_1     |     manager = TaskManager(
crawler_1     |   File "/opt/OpenWPM/openwpm/task_manager.py", line 132, in __init__
crawler_1     |     openwpm_v, browser_v = get_version()
crawler_1     |   File "/opt/OpenWPM/openwpm/utilities/platform_utils.py", line 84, in get_version
crawler_1     |     raise RuntimeError("Firefox not found. " " Did you run `./install.sh`?") from e
crawler_1     | RuntimeError: Firefox not found.  Did you run `./install.sh`?

I have firefox installed on my mac...
can anyone help? I'm pretty new to this so I have a little knowledge... I just need to run a simple  crawl on a URL's list
thanks

**Comment by vringar** [comment]
Hey,
thank you for bringing this to my attention.
Apparently Firefox's dependencies had changed and we hadn't noticed.
I will adjust the dependencies and then make a new release.
This way the docker-compose file should be working in a couple of hours.

**Comment by sal123-droid** [comment]
Hey, thank you for your comment.
I'm still getting the same error message... do you know what else can be done?
thanks!

**Comment by vringar** [comment]
Hey, could you try again now?

**Comment by sal123-droid** [comment]
I'm just running the `docker-compose up crawler` command from the openwpm-crawler/deployment/local-compose folder and still getting the same error message...
should I do something else?
thanks

**Comment by vringar** [comment]
So sorry that this is broken I filed #57 due to this problem being different than the original.
